# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech/proto_speech/orderinfo2user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech/proto_speech/orderinfo2user.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(speech/proto_speech/orderinfo2user.proto\"\x16\n\x05\x44ummy\x12\r\n\x05\x64ummy\x18\x01 \x01(\t\"$\n\x0cOrderDetails\x12\x14\n\x0cinfoReceived\x18\x01 \x01(\t2?\n\x0eOrderInfo2User\x12-\n\x10SendOrderDetails\x12\x06.Dummy\x1a\r.OrderDetails\"\x00\x30\x01\x62\x06proto3')
)




_DUMMY = _descriptor.Descriptor(
  name='Dummy',
  full_name='Dummy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dummy', full_name='Dummy.dummy', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=66,
)


_ORDERDETAILS = _descriptor.Descriptor(
  name='OrderDetails',
  full_name='OrderDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='infoReceived', full_name='OrderDetails.infoReceived', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['Dummy'] = _DUMMY
DESCRIPTOR.message_types_by_name['OrderDetails'] = _ORDERDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), dict(
  DESCRIPTOR = _DUMMY,
  __module__ = 'speech.proto_speech.orderinfo2user_pb2'
  # @@protoc_insertion_point(class_scope:Dummy)
  ))
_sym_db.RegisterMessage(Dummy)

OrderDetails = _reflection.GeneratedProtocolMessageType('OrderDetails', (_message.Message,), dict(
  DESCRIPTOR = _ORDERDETAILS,
  __module__ = 'speech.proto_speech.orderinfo2user_pb2'
  # @@protoc_insertion_point(class_scope:OrderDetails)
  ))
_sym_db.RegisterMessage(OrderDetails)



_ORDERINFO2USER = _descriptor.ServiceDescriptor(
  name='OrderInfo2User',
  full_name='OrderInfo2User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendOrderDetails',
    full_name='OrderInfo2User.SendOrderDetails',
    index=0,
    containing_service=None,
    input_type=_DUMMY,
    output_type=_ORDERDETAILS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERINFO2USER)

DESCRIPTOR.services_by_name['OrderInfo2User'] = _ORDERINFO2USER

# @@protoc_insertion_point(module_scope)
