# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from temp.proto_order import temp1_pb2 as temp_dot_proto__order_dot_temp1__pb2


class MessageTransmissionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/MessageTransmission/sendMessage',
        request_serializer=temp_dot_proto__order_dot_temp1__pb2.Message.SerializeToString,
        response_deserializer=temp_dot_proto__order_dot_temp1__pb2.Message.FromString,
        )


class MessageTransmissionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageTransmissionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=temp_dot_proto__order_dot_temp1__pb2.Message.FromString,
          response_serializer=temp_dot_proto__order_dot_temp1__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MessageTransmission', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
