# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from temp.proto_order import temp2_pb2 as temp_dot_proto__order_dot_temp2__pb2


class HelloUserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateStream = channel.unary_stream(
        '/HelloUser/CreateStream',
        request_serializer=temp_dot_proto__order_dot_temp2__pb2.Connect.SerializeToString,
        response_deserializer=temp_dot_proto__order_dot_temp2__pb2.Message.FromString,
        )
    self.BroadcastMessage = channel.unary_stream(
        '/HelloUser/BroadcastMessage',
        request_serializer=temp_dot_proto__order_dot_temp2__pb2.Message.SerializeToString,
        response_deserializer=temp_dot_proto__order_dot_temp2__pb2.Close.FromString,
        )


class HelloUserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BroadcastMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloUserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateStream': grpc.unary_stream_rpc_method_handler(
          servicer.CreateStream,
          request_deserializer=temp_dot_proto__order_dot_temp2__pb2.Connect.FromString,
          response_serializer=temp_dot_proto__order_dot_temp2__pb2.Message.SerializeToString,
      ),
      'BroadcastMessage': grpc.unary_stream_rpc_method_handler(
          servicer.BroadcastMessage,
          request_deserializer=temp_dot_proto__order_dot_temp2__pb2.Message.FromString,
          response_serializer=temp_dot_proto__order_dot_temp2__pb2.Close.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HelloUser', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
